apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
images:
- name: quay.io/openshift-virtualization/virt-platform-autopilot
  newName: quay.io/openshift-virtualization/virt-platform-autopilot
  newTag: v0.0.9
- name: virt-platform-autopilot
  newName: quay.io/openshift-virtualization/virt-platform-autopilot
  newTag: v0.0.9
