apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubevirt-metrics-exporter
  namespace: kubevirt-metrics-exporter
  labels:
    app: kubevirt-metrics-exporter
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: kubevirt-metrics-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true
