#!/usr/bin/env bash

# Fetch kubevirt-metrics-exporter deploy manifests from GitHub and sync them into
# assets/active/kubevirt-metrics-exporter/, applying autopilot-specific transforms
# to the DaemonSet. Also rewrites (or verifies) the kubevirt-metrics-exporter block
# in assets/active/metadata.yaml in the same sequential asset order.
#
# Usage:
#   ./hack/sync-kme-assets.sh           - fetch and sync
#   ./hack/sync-kme-assets.sh --verify  - verify assets match upstream (for CI)
#
# Optional env: KME_FORK=openshift-virtualization/kubevirt-metrics-exporter KME_BRANCH=main

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEST_DIR="${REPO_ROOT}/assets/active/kubevirt-metrics-exporter"
METADATA_FILE="${REPO_ROOT}/assets/active/metadata.yaml"
KME_FORK="${KME_FORK:-openshift-virtualization/kubevirt-metrics-exporter}"
KME_BRANCH="${KME_BRANCH:-main}"
VERIFY=false
TEMP_DIR=""
FAILED=0

# Exact header line emitted by generate_metadata_block(); also the metadata replace span start.
METADATA_MARKER='  # The following KME assets are generated by hack/sync-kme-assets.sh — do not edit by hand.'

# shellcheck disable=SC2016 # $envOverrides is Helm syntax, not shell expansion
TEMPLATE_HEADER='{{- $envOverrides := dig "metadata" "annotations" "platform.kubevirt.io/kubevirt-metrics-exporter-env" "{}" .HCO.Object | fromJson }}'

# Ordered asset list. First entry defines &kubevirt-metrics-exporter-conditions;
# later entries alias it.
# Format: mode|reconcile_order|upstream_relpath|dest_name
#   mode=copy      — fetch upstream and copy as-is
#   mode=daemonset — fetch upstream and apply DaemonSet transform
declare -a ASSETS=(
	"copy|1|deploy/base/namespace.yaml|namespace.yaml"
	"copy|2|deploy/base/serviceaccount.yaml|serviceaccount.yaml"
	"copy|2|deploy/base/clusterrole.yaml|clusterrole.yaml"
	"copy|2|deploy/base/clusterrolebinding.yaml|clusterrolebinding.yaml"
	"copy|2|deploy/openshift/scc.yaml|scc.yaml"
	"copy|2|deploy/openshift/scc-clusterrole.yaml|scc-clusterrole.yaml"
	"copy|2|deploy/openshift/scc-clusterrolebinding.yaml|scc-clusterrolebinding.yaml"
	"copy|3|deploy/openshift/metrics-service.yaml|service.yaml"
	"daemonset|4|deploy/base/daemonset.yaml|kubevirt-metrics-exporter.yaml.tpl"
	"copy|4|deploy/openshift/metrics-servicemonitor.yaml|servicemonitor.yaml"
	"copy|3|deploy/prometheus-rules/prometheusrule.yaml|prometheusrule.yaml"
	"copy|3|deploy/prometheus-rules/recording/cpu.yaml|prometheusrule-recording-cpu.yaml"
	"copy|3|deploy/prometheus-rules/recording/io.yaml|prometheusrule-recording-io.yaml"
	"copy|3|deploy/prometheus-rules/recording/memory.yaml|prometheusrule-recording-memory.yaml"
	"copy|3|deploy/openshift/datasource.yaml|datasource.yaml"
	"copy|3|deploy/openshift/dashboard-overview.yaml|dashboard.yaml"
	"copy|3|deploy/openshift/dashboard-cpu.yaml|dashboard-cpu.yaml"
	"copy|3|deploy/openshift/dashboard-io.yaml|dashboard-io.yaml"
	"copy|3|deploy/openshift/dashboard-memory.yaml|dashboard-memory.yaml"
	"copy|3|deploy/openshift/dashboard-io-latency.yaml|dashboard-io-latency.yaml"
	"copy|3|deploy/openshift/dashboard-memory-detailed.yaml|dashboard-memory-detailed.yaml"
)

cleanup() {
	if [[ -n "${TEMP_DIR}" && -d "${TEMP_DIR}" ]]; then
		rm -rf "${TEMP_DIR}"
	fi
}
trap cleanup EXIT

usage() {
	cat <<EOF
Usage:
	${0##*/}           Fetch and sync assets (+ rewrite metadata.yaml KME block)
  ${0##*/} --verify  Verify assets and metadata match expected (for CI)

Removals (dest files or metadata entries present in autopilot but not in ASSETS):
  sync     — warn only (stale dest files left in place)
  --verify — fail

Optional env:
  KME_FORK=owner/repo   GitHub slug (default: upstream)
  KME_BRANCH=main
EOF
}

upstream_url() {
	local relpath=$1
	printf 'https://raw.githubusercontent.com/%s/%s/%s' "${KME_FORK}" "${KME_BRANCH}" "${relpath}"
}

fetch_upstream() {
	local relpath=$1
	local dest=$2
	mkdir -p "$(dirname "${dest}")"
	curl -sSfL "$(upstream_url "${relpath}")" -o "${dest}"
}

write_or_compare_file() {
	local dest=$1
	local src=$2

	if [[ "${VERIFY}" == true ]]; then
		if [[ ! -f "${dest}" ]]; then
			echo "  ✗ MISSING ${dest}" >&2
			FAILED=1
			return
		fi
		if cmp -s "${src}" "${dest}"; then
			echo "  ✓ ${dest}"
		else
			echo "  ✗ OUT OF SYNC ${dest}" >&2
			FAILED=1
		fi
		return
	fi

	mkdir -p "$(dirname "${dest}")"
	cp "${src}" "${dest}"
	echo "  ✓ ${dest}"
}

transform_daemonset() {
	local src=$1
	printf '%s\n' "${TEMPLATE_HEADER}"
	sed -e 's|^[[:space:]]*image:.*|          image: {{ index .Images "kubevirt-metrics-exporter" }}|' \
		-e 's/containerPort: 8080/containerPort: 8443/' \
		-e '/hostPID: true/a\
      nodeSelector:\
        node-role.kubernetes.io/worker: ""
' "${src}" | awk '
/^[[:space:]]+env:/ {
	match($0, /^[[:space:]]+/)
	env_indent = substr($0, RSTART, RLENGTH)
	print
	printf "%s  - name: LISTEN_ADDRESS\n%s    value: \":8443\"\n", env_indent, env_indent
	printf "%s  - name: TLS_CERT_FILE\n%s    value: \"/etc/tls/private/tls.crt\"\n", env_indent, env_indent
	printf "%s  - name: TLS_KEY_FILE\n%s    value: \"/etc/tls/private/tls.key\"\n", env_indent, env_indent
	printf "%s  - name: TLS_MIN_VERSION\n%s    value: {{ resolvedTLSMinVersion | quote }}\n", env_indent, env_indent
	printf "%s  - name: TLS_CIPHER_SUITES\n%s    value: {{ resolvedTLSCipherSuites | quote }}\n", env_indent, env_indent
	next
}
/^[[:space:]]+volumeMounts:/ {
	match($0, /^[[:space:]]+/)
	indent = substr($0, RSTART, RLENGTH)
	print
	printf "%s  - name: metrics-serving-cert\n%s    mountPath: /etc/tls/private\n%s    readOnly: true\n", indent, indent, indent
	next
}
/^[[:space:]]+volumes:/ {
	match($0, /^[[:space:]]+/)
	indent = substr($0, RSTART, RLENGTH)
	print
	printf "%s  - name: metrics-serving-cert\n%s    secret:\n%s      secretName: kubevirt-metrics-exporter-tls\n", indent, indent, indent
	next
}
/^[[:space:]]+- name: / {
	match($0, /^[[:space:]]+/)
	env_indent = substr($0, RSTART, RLENGTH)
	split($0, parts, "name: ")
	current_env = parts[2]
	gsub(/[[:space:]]+/, "", current_env)
	print
	next
}
/^[[:space:]]+valueFrom:/ {
	current_env = "NODE_NAME"
	print
	next
}
/^[[:space:]]+value:/ && current_env != "" && current_env != "NODE_NAME" {
	split($0, value_parts, "value:")
	default_val = value_parts[2]
	gsub(/^[[:space:]]+/, "", default_val)
	gsub(/^"/, "", default_val)
	gsub(/"$/, "", default_val)
	printf "%s  value: {{ index $envOverrides \"%s\" | default \"%s\" | quote }}\n", env_indent, current_env, default_val
	next
}
{ print }
'
}

asset_stem() {
	local dest=$1
	local stem="${dest%.yaml.tpl}"
	stem="${stem%.yaml}"
	printf '%s' "${stem}"
}

asset_meta_name() {
	local dest=$1
	local stem
	stem="$(asset_stem "${dest}")"
	if [[ "${stem}" == "kubevirt-metrics-exporter" ]]; then
		printf '%s' "${stem}"
	else
		printf 'kubevirt-metrics-exporter-%s' "${stem}"
	fi
}

kind_from_file() {
	local file=$1
	# Skip leading Helm/template lines; first YAML kind: wins.
	awk '
		/^[[:space:]]*kind:[[:space:]]*/ {
			sub(/^[[:space:]]*kind:[[:space:]]*/, "")
			print
			exit
		}
	' "${file}"
}

generate_metadata_block() {
	local dest_dir=$1
	local entry mode order upstream dest name kind first=true

	printf '%s\n' "${METADATA_MARKER}"

	for entry in "${ASSETS[@]}"; do
		IFS='|' read -r mode order upstream dest <<< "${entry}"
		name="$(asset_meta_name "${dest}")"
		kind="$(kind_from_file "${dest_dir}/${dest}")"
		if [[ -z "${kind}" ]]; then
			echo "failed to detect kind in ${dest_dir}/${dest}" >&2
			return 1
		fi
		if [[ -z "${order}" ]]; then
			echo "missing reconcile_order in ASSETS entry: ${entry}" >&2
			return 1
		fi

		if [[ "${first}" == true ]]; then
			cat <<EOF

  - name: ${name}
    group: kubevirt-metrics-exporter
    path: active/kubevirt-metrics-exporter/${dest}
    phase: 1
    install: opt-in
    component: ${kind}
    reconcile_order: ${order}
    conditions: &kubevirt-metrics-exporter-conditions
      - type: annotation
        key: platform.kubevirt.io/enable-kubevirt-metrics-exporter
        value: "true"
      - type: image
        key: kubevirt-metrics-exporter
EOF
			first=false
			continue
		fi

		cat <<EOF

  - name: ${name}
    group: kubevirt-metrics-exporter
    path: active/kubevirt-metrics-exporter/${dest}
    phase: 1
    install: opt-in
    component: ${kind}
    reconcile_order: ${order}
    conditions: *kubevirt-metrics-exporter-conditions
EOF
	done
}

# Locate the contiguous metadata span for group: kubevirt-metrics-exporter.
# Prints "start_line end_line" as 0-based half-open indices (start inclusive, end exclusive).
# Span starts at METADATA_MARKER (required; same line generate_metadata_block emits).
find_kme_metadata_span() {
	local file=$1
	python3 - "${file}" "${METADATA_MARKER}" <<'PY'
import sys
from pathlib import Path

lines = Path(sys.argv[1]).read_text().splitlines(keepends=True)
marker = sys.argv[2]

def entry_group(start: int):
    """Return group value for the asset entry starting at lines[start] ('  - name:')."""
    j = start + 1
    while j < len(lines) and not lines[j].startswith("  - name:"):
        stripped = lines[j].lstrip()
        if stripped.startswith("group:"):
            return stripped.split(":", 1)[1].strip()
        j += 1
    return None

marker_indexes = [i for i, line in enumerate(lines) if line.rstrip("\n") == marker.rstrip("\n")]
if not marker_indexes:
    raise SystemExit(f"missing metadata marker line: {marker.rstrip()!r}")

name_indexes = [i for i, line in enumerate(lines) if line.startswith("  - name:")]
kme_indexes = [i for i in name_indexes if entry_group(i) == "kubevirt-metrics-exporter"]
if not kme_indexes:
    raise SystemExit("no metadata assets with group: kubevirt-metrics-exporter")

first = kme_indexes[0]
last = first
for idx in name_indexes:
    if idx < first:
        continue
    if entry_group(idx) == "kubevirt-metrics-exporter":
        last = idx
    else:
        break

# Use the earliest marker that sits above the first KME asset (handles duplicates).
start = None
for i in marker_indexes:
    if i < first:
        start = i
        break
if start is None:
    raise SystemExit(
        f"metadata marker {marker.rstrip()!r} must appear above the first "
        "kubevirt-metrics-exporter asset"
    )

end = len(lines)
for idx in name_indexes:
    if idx > last:
        end = idx
        break

while end > start and lines[end - 1].strip() == "":
    end -= 1

print(f"{start} {end}")
PY
}

extract_metadata_block() {
	local file=$1
	local span start end
	span="$(find_kme_metadata_span "${file}")"
	start="${span%% *}"
	end="${span##* }"
	python3 - "${file}" "${start}" "${end}" <<'PY'
import sys
from pathlib import Path
lines = Path(sys.argv[1]).read_text().splitlines(keepends=True)
start, end = int(sys.argv[2]), int(sys.argv[3])
sys.stdout.write("".join(lines[start:end]))
if start < end and not lines[end - 1].endswith("\n"):
    sys.stdout.write("\n")
PY
}

replace_metadata_block() {
	local file=$1
	local new_block_file=$2
	local tmp span start end
	tmp="$(mktemp)"
	span="$(find_kme_metadata_span "${file}")"
	start="${span%% *}"
	end="${span##* }"

	python3 - "${file}" "${new_block_file}" "${tmp}" "${start}" "${end}" <<'PY'
import sys
from pathlib import Path

src_path = Path(sys.argv[1])
block = Path(sys.argv[2]).read_text()
out_path = Path(sys.argv[3])
start, end = int(sys.argv[4]), int(sys.argv[5])
lines = src_path.read_text().splitlines(keepends=True)

def ensure_nl(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"

new_lines = lines[:start]
block = ensure_nl(block).rstrip("\n") + "\n"
new_lines.append(block)
if end < len(lines):
    # Exactly one blank line between the KME block and the next asset.
    if lines[end].startswith("  - name:"):
        new_lines.append("\n")
    new_lines.extend(lines[end:])
out_path.write_text("".join(new_lines))
PY

	mv "${tmp}" "${file}"
}

sync_or_verify_metadata() {
	local expected
	expected="$(mktemp)"
	# Prefer dest dir contents (already synced/verified assets) for kind detection.
	generate_metadata_block "${DEST_DIR}" > "${expected}"

	if [[ "${VERIFY}" == true ]]; then
		local current
		current="$(mktemp)"
		if ! extract_metadata_block "${METADATA_FILE}" > "${current}"; then
			echo "  ✗ MISSING kubevirt-metrics-exporter group block in ${METADATA_FILE}" >&2
			FAILED=1
			rm -f "${expected}" "${current}"
			return
		fi
		# Normalize trailing newlines for stable comparison.
		python3 - "${expected}" "${current}" <<'PY'
import sys
from pathlib import Path
for p in sys.argv[1:]:
    path = Path(p)
    text = path.read_text().rstrip("\n") + "\n"
    path.write_text(text)
PY
		if cmp -s "${expected}" "${current}"; then
			echo "  ✓ ${METADATA_FILE} (kubevirt-metrics-exporter block)"
		else
			echo "  ✗ OUT OF SYNC ${METADATA_FILE} (kubevirt-metrics-exporter block)" >&2
			FAILED=1
		fi
		rm -f "${expected}" "${current}"
		return
	fi

	replace_metadata_block "${METADATA_FILE}" "${expected}"
	echo "  ✓ ${METADATA_FILE} (kubevirt-metrics-exporter block)"
	rm -f "${expected}"
}

expected_asset_dests() {
	local entry mode order upstream dest
	for entry in "${ASSETS[@]}"; do
		IFS='|' read -r mode order upstream dest <<< "${entry}"
		printf '%s\n' "${dest}"
	done
}

# Assets present in autopilot but absent from ASSETS need tombstoning before removal.
# Sync: warn only. Verify: fail.
report_removed_assets() {
	local expected_file
	local f base name path
	expected_file="$(mktemp)"
	expected_asset_dests | sort -u > "${expected_file}"

	shopt -s nullglob
	for f in "${DEST_DIR}"/*; do
		base="$(basename "${f}")"
		if ! grep -qxF "${base}" "${expected_file}"; then
			if [[ "${VERIFY}" == true ]]; then
				echo "  ✗ REMOVED dest (tombstone required): ${f}" >&2
				FAILED=1
			else
				echo "  ! WARN dest present in autopilot but not in ASSETS (tombstone required before removal): ${f}" >&2
			fi
		fi
	done
	shopt -u nullglob

	while IFS=$'\t' read -r name path; do
		[[ -z "${path}" ]] && continue
		base="$(basename "${path}")"
		if ! grep -qxF "${base}" "${expected_file}"; then
			if [[ "${VERIFY}" == true ]]; then
				echo "  ✗ REMOVED metadata asset (tombstone required): ${name} (${path})" >&2
				FAILED=1
			else
				echo "  ! WARN metadata asset present but not in ASSETS (tombstone required before removal): ${name} (${path})" >&2
			fi
		fi
	done < <(python3 - "${METADATA_FILE}" <<'PY'
import sys
from pathlib import Path

lines = Path(sys.argv[1]).read_text().splitlines()
i = 0
while i < len(lines):
    if lines[i].startswith("  - name:"):
        name = lines[i].split(":", 1)[1].strip()
        group = path = None
        j = i + 1
        while j < len(lines) and not lines[j].startswith("  - name:"):
            s = lines[j].strip()
            if s.startswith("group:"):
                group = s.split(":", 1)[1].strip()
            elif s.startswith("path:"):
                path = s.split(":", 1)[1].strip()
            j += 1
        if group == "kubevirt-metrics-exporter" and path:
            print(f"{name}\t{path}")
        i = j
    else:
        i += 1
PY
)

	rm -f "${expected_file}"
}

sync_assets() {
	local entry mode order upstream dest src

	for entry in "${ASSETS[@]}"; do
		IFS='|' read -r mode order upstream dest <<< "${entry}"
		src="${TEMP_DIR}/${upstream}"
		case "${mode}" in
		copy)
			write_or_compare_file "${DEST_DIR}/${dest}" "${src}"
			;;
		daemonset)
			local daemonset_tmp
			daemonset_tmp="$(mktemp)"
			transform_daemonset "${src}" > "${daemonset_tmp}"
			write_or_compare_file "${DEST_DIR}/${dest}" "${daemonset_tmp}"
			rm -f "${daemonset_tmp}"
			;;
		*)
			echo "unknown asset mode: ${mode}" >&2
			exit 1
			;;
		esac
	done

	report_removed_assets
	sync_or_verify_metadata
}

main() {
	if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
		usage
		exit 0
	fi
	if [[ "${1:-}" == "--verify" ]]; then
		VERIFY=true
	fi

	TEMP_DIR="$(mktemp -d)"

	echo "$([[ "${VERIFY}" == true ]] && echo Verifying || echo Syncing) kubevirt-metrics-exporter assets from https://github.com/${KME_FORK}.git@${KME_BRANCH}"

	local entry mode order upstream dest
	for entry in "${ASSETS[@]}"; do
		IFS='|' read -r mode order upstream dest <<< "${entry}"
		fetch_upstream "${upstream}" "${TEMP_DIR}/${upstream}"
	done

	sync_assets

	if [[ "${VERIFY}" == true ]]; then
		if [[ "${FAILED}" -eq 0 ]]; then
			echo "✓ All kubevirt-metrics-exporter assets are in sync with KME"
			exit 0
		fi
		echo "✗ kubevirt-metrics-exporter assets are out of sync with KME" >&2
		exit 1
	fi

	if [[ "${FAILED}" -ne 0 ]]; then
		exit 1
	fi

	echo "✓ Sync complete"
}

main "$@"
