/*
Copyright 2026 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// rbac-gen scans the assets/ directory and writes config/rbac/role.yaml with all
// ClusterRole rules required by virt-platform-autopilot.  Run via 'make generate-rbac'.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/kubevirt/virt-platform-autopilot/pkg/rbac"
)

const outputFile = "config/rbac/role.yaml"

func main() {
	dryRun := flag.Bool("dry-run", false, "Print generated RBAC to stdout instead of writing to file")
	flag.Parse()

	if !*dryRun {
		fmt.Println("Scanning assets for resources...")
	}

	// Scan the real assets/ directory on disk
	rules, err := rbac.AllRules(os.DirFS("assets"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning assets: %v\n", err)
		os.Exit(1)
	}

	staticCount := len(rbac.StaticRules())
	dynamicCount := len(rules) - staticCount

	if !*dryRun {
		fmt.Printf("Found %d unique resource types\n", dynamicCount)
		fmt.Printf("Generated %d dynamic RBAC rules\n", dynamicCount)
	}

	header := `# AUTO-GENERATED by 'make generate-rbac'
# DO NOT EDIT MANUALLY - your changes will be overwritten
# To modify RBAC:
#   1. Add/remove assets in assets/ directory
#   2. Run 'make generate-rbac'
#   3. Commit the updated config/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virt-platform-autopilot-role
rules:
`

	rulesYAML := formatRulesWithComments(rules)
	output := header + rulesYAML

	if *dryRun {
		fmt.Print(output)
		return
	}

	if err := os.WriteFile(outputFile, []byte(output), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing to %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("✓ RBAC ClusterRole written to %s\n", outputFile)
	fmt.Printf("  Total rules: %d (%d static + %d dynamic)\n", len(rules), staticCount, dynamicCount)
}

// formatRulesWithComments renders all rules as YAML with human-readable section comments.
// The first len(StaticRules()) rules are the static infrastructure rules; the rest are dynamic.
func formatRulesWithComments(rules []rbac.Rule) string {
	staticCount := len(rbac.StaticRules())
	var b strings.Builder

	b.WriteString("  # ========================================\n")
	b.WriteString("  # Operator Infrastructure (Static)\n")
	b.WriteString("  # ========================================\n")
	b.WriteString("  # Nodes (for hardware detection)\n")
	writeRule(&b, rules[0])
	b.WriteString("  # Events (for observability - legacy core/v1 API)\n")
	writeRule(&b, rules[1])
	b.WriteString("  # Events (for observability - modern events.k8s.io/v1 API)\n")
	writeRule(&b, rules[2])
	b.WriteString("  # Leader Election\n")
	writeRule(&b, rules[3])
	b.WriteString("  # CRD Discovery (for soft dependency detection and template introspection)\n")
	writeRule(&b, rules[4])
	b.WriteString("  # OpenShift Infrastructure CR (for topology detection: HCP, compact, cloud provider)\n")
	writeRule(&b, rules[5])

	b.WriteString("  # ========================================\n")
	b.WriteString("  # Managed Resources (Dynamic - from assets/)\n")
	b.WriteString("  # ========================================\n")

	for i := staticCount; i < len(rules); i++ {
		rule := rules[i]
		comment := commentForAPIGroup(rule.APIGroups[0])

		hasDelete := false
		for _, v := range rule.Verbs {
			if v == "delete" {
				hasDelete = true
				break
			}
		}

		if comment != "" {
			if hasDelete {
				fmt.Fprintf(&b, "  # %s (includes tombstone cleanup)\n", comment)
			} else {
				fmt.Fprintf(&b, "  # %s\n", comment)
			}
		}
		writeRule(&b, rule)
	}

	return b.String()
}

func writeRule(b *strings.Builder, rule rbac.Rule) {
	b.WriteString("  - apiGroups:\n")
	for _, group := range rule.APIGroups {
		if group == "" {
			b.WriteString("      - \"\"\n")
		} else {
			fmt.Fprintf(b, "      - %s\n", group)
		}
	}
	b.WriteString("    resources:\n")
	for _, r := range rule.Resources {
		fmt.Fprintf(b, "      - %s\n", r)
	}
	b.WriteString("    verbs:\n")
	for _, v := range rule.Verbs {
		fmt.Fprintf(b, "      - %s\n", v)
	}
}

func commentForAPIGroup(group string) string {
	switch group {
	case "config.openshift.io":
		return "OpenShift Infrastructure"
	case "hco.kubevirt.io":
		return "HyperConverged"
	case "machineconfiguration.openshift.io":
		return "MachineConfig & KubeletConfig"
	case "operator.openshift.io":
		return "KubeDescheduler"
	case "remediation.medik8s.io":
		return "NodeHealthCheck"
	case "self-node-remediation.medik8s.io":
		return "Self Node Remediation"
	case "fence-agents-remediation.medik8s.io":
		return "Fence Agents Remediation"
	case "forklift.konveyor.io":
		return "Migration Toolkit for Virtualization (MTV)"
	case "metallb.io":
		return "MetalLB"
	case "monitoring.coreos.com":
		return "Prometheus Alert Rules"
	case "observability.openshift.io":
		return "Cluster Observability"
	default:
		return ""
	}
}
