apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: thanos-querier
  namespace: kubevirt-metrics-exporter
  labels:
    app: kubevirt-metrics-exporter
spec:
  config:
    display:
      name: "Thanos Querier"
    default: true
    plugin:
      kind: "PrometheusDatasource"
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
            secret: thanos-querier-secret
  client:
    tls:
      enable: true
      caCert:
        type: file
        certPath: /ca/service-ca.crt
