apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubevirt-metrics-exporter
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
allowedCapabilities:
  - SYS_PTRACE
  - DAC_OVERRIDE
  - BPF
  - PERFMON
  - SYS_RESOURCE
defaultAddCapabilities: []
requiredDropCapabilities:
  - ALL
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - projected
  - secret
