apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: vm-restore-rules
spec:
  component: kubevirt
  target:
    group: snapshot.kubevirt.io
    version: v1beta1
    resource: virtualmachinerestores
  rules:
    - operation: InProgress
      expression: |
        has(object.status) && has(object.status.phase) && object.status.phase == "InProgress"

    - operation: Failed
      expression: |
        has(object.status) && has(object.status.phase) && object.status.phase == "Failed"
