apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: clusteroperator-rules
spec:
  component: openshift
  labels:
    ifo.kubevirt.io/correlation-group: cluster-update
    ifo.kubevirt.io/correlation-role: child
  target:
    group: config.openshift.io
    version: v1
    resource: clusteroperators
  rules:
    - operation: Deploying
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Available" && c.status == "False") &&
        object.status.conditions.exists(c, c.type == "Progressing" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Degraded" && c.status == "False")
    - operation: Reconciling
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Available" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Progressing" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Degraded" && c.status == "False")
    - operation: ReconcilingDegraded
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Available" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Progressing" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Degraded" && c.status == "True")
    - operation: Healing
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Available" && c.status == "False") &&
        object.status.conditions.exists(c, c.type == "Progressing" && c.status == "True") &&
        object.status.conditions.exists(c, c.type == "Degraded" && c.status == "True")
    - operation: Failing
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Available" && c.status == "False") &&
        object.status.conditions.exists(c, c.type == "Progressing" && c.status == "False") &&
        object.status.conditions.exists(c, c.type == "Degraded" && c.status == "True")
    - operation: NotUpgradeable
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Upgradeable" && c.status == "False")
