apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: storageversionmigration-rules
spec:
  component: openshift
  labels:
    ifo.kubevirt.io/correlation-group: cluster-update
    ifo.kubevirt.io/correlation-role: child
  target:
    group: migration.k8s.io
    version: v1alpha1
    resource: storageversionmigrations
  rules:
    - operation: Migrating
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "Running" && c.status == "True")
