apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: installplan-rules
spec:
  component: olm
  labels:
    ifo.kubevirt.io/correlation-group: olm-install
    ifo.kubevirt.io/correlation-role: child
  target:
    group: operators.coreos.com
    version: v1alpha1
    resource: installplans
  rules:
    - operation: Planning
      expression: |
        has(object.status) &&
        has(object.status.phase) &&
        object.status.phase == "Planning"

    - operation: Installing
      expression: |
        has(object.status) &&
        has(object.status.phase) &&
        object.status.phase == "Installing"

    - operation: RequiresApproval
      expression: |
        has(object.status) &&
        has(object.status.phase) &&
        object.status.phase == "RequiresApproval"

