apiVersion: ifo.kubevirt.io/v1alpha1
kind: OperationRuleSet
metadata:
  name: subscription-rules
spec:
  component: olm
  labels:
    ifo.kubevirt.io/correlation-group: olm-install
    ifo.kubevirt.io/correlation-role: root
  target:
    group: operators.coreos.com
    version: v1alpha1
    resource: subscriptions
  rules:
    - operation: Unpacking
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "BundleUnpacking")
    - operation: InstallPlanPending
      expression: |
        has(object.status) &&
        has(object.status.conditions) &&
        object.status.conditions.exists(c, c.type == "InstallPlanPending")
